"""delete table user_transaction_association

Revision ID: 4c66c1fb436e
Revises: e1b2d7ec7005
Create Date: 2024-07-07 18:07:14.960392

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4c66c1fb436e"
down_revision: Union[str, None] = "e1b2d7ec7005"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_transaction_association")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_transaction_association",
        sa.Column(
            "user_transaction_id", sa.INTEGER(), autoincrement=True, nullable=False
        ),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("transaction_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transactions.transaction_id"],
            name="user_transaction_association_transaction_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
            name="user_transaction_association_user_id_fkey",
        ),
        sa.PrimaryKeyConstraint(
            "user_transaction_id", name="user_transaction_association_pkey"
        ),
        sa.UniqueConstraint(
            "user_id", "transaction_id", name="idx_unique_user_transaction_association"
        ),
    )
    # ### end Alembic commands ###
