"""add column is_active to User model

Revision ID: 52256804283c
Revises: 4c66c1fb436e
Create Date: 2024-07-08 01:40:27.920441

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "52256804283c"
down_revision: Union[str, None] = "4c66c1fb436e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("is_active", sa.Boolean(), server_default="True", nullable=False),
    )
    op.alter_column(
        "users",
        "password",
        existing_type=sa.VARCHAR(length=255),
        type_=postgresql.BYTEA(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "password",
        existing_type=postgresql.BYTEA(),
        type_=sa.VARCHAR(length=255),
        existing_nullable=False,
    )
    op.drop_column("users", "is_active")
    # ### end Alembic commands ###
