"""create user trasaction association table

Revision ID: 977bf6882b79
Revises: 778f5b7dbcaf
Create Date: 2024-07-06 15:20:33.282015

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "977bf6882b79"
down_revision: Union[str, None] = "778f5b7dbcaf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_transaction_association",
        sa.Column("user_transaction_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("transaction_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transactions.transaction_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("user_transaction_id"),
        sa.UniqueConstraint(
            "user_id", "transaction_id", name="idx_unique_user_transaction_association"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_transaction_association")
    # ### end Alembic commands ###
