"""add category_id to transaction

Revision ID: cbf850c86528
Revises: 11aeb0317d04
Create Date: 2024-07-04 23:26:42.367455

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cbf850c86528"
down_revision: Union[str, None] = "11aeb0317d04"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("transactions", sa.Column("category_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None, "transactions", "categories", ["category_id"], ["category_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "transactions", type_="foreignkey")
    op.drop_column("transactions", "category_id")
    # ### end Alembic commands ###
