"""add category_id to Goal

Revision ID: db9cca565714
Revises: cbf850c86528
Create Date: 2024-07-04 23:31:22.475751

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "db9cca565714"
down_revision: Union[str, None] = "cbf850c86528"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("budgets", "category")
    op.add_column("goals", sa.Column("category_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "goals", "categories", ["category_id"], ["category_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "goals", type_="foreignkey")
    op.drop_column("goals", "category_id")
    op.add_column(
        "budgets",
        sa.Column("category", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
