"""add category_id to budget model

Revision ID: e1b2d7ec7005
Revises: 977bf6882b79
Create Date: 2024-07-06 16:13:41.997801

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e1b2d7ec7005"
down_revision: Union[str, None] = "977bf6882b79"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("budgets", sa.Column("category_id", sa.Integer(), nullable=False))
    op.create_foreign_key(
        None, "budgets", "categories", ["category_id"], ["category_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "budgets", type_="foreignkey")
    op.drop_column("budgets", "category_id")
    # ### end Alembic commands ###
